### ISSUE TITLE
Allow variable scale factors

### ISSUE THREAD

**Issue by DWindhorst** [jlu-ilr-hydro/odmf#33]
Allow users to use the parameter "factor" to hand over a reference to a column with variable scale factors instead of a fixed number. 

Eg: "factor=column:32"

Reason: We have measured diluted samples with various dilution factors, and would require this feature to correct the values.

**Comment by DWindhorst** [comment]
Any update on this issue?

**Comment by philippkraft** [comment]
661c8e184f6f5b53b3259bd04d007a86d1ed01e8 contains a try on variable scale factor, testing needed. Can be used with a fixed factor together (eg. for unit conversion)

Usage:

    factor_column=32

**Comment by philippkraft** [comment]
Can be manged by calculated Excel  columns
