### ISSUE TITLE
Schwingbach database is slow in responding

### ISSUE THREAD

**Issue by thouska** [jlu-ilr-hydro/odmf#41]
Might be caused by low remaining disk space of only 1GB.

**Comment by philippkraft** [comment]
Cannot reproduce- database is runniong fine for me. Please provide steps t reproduce the problem. If it does not persist, please close the issue.

**Comment by thouska** [comment]
Issue remains, if working in the "Jobs" section of the database. 
Everything else runs nice and smooth.

**Comment by philippkraft** [comment]
I guess this is solved by now?
