### ISSUE TITLE
Jobs in the Schwingbach database can only sometimes be marked as done

### ISSUE THREAD

**Issue by thouska** [jlu-ilr-hydro/odmf#42]
Reponse of the Schwingbach database is very slow when working with the Jobs section on the database. Active Jobs are not shown for the users and can only made visible by marking "all jobs". Marking the jobs as done, is only working in around 20% of trials. This issue might be linked to #41

**Comment by philippkraft** [comment]
Cannot reproduce, does the proble still exist?
