### ISSUE TITLE
Refactoring: Missing styles and js files

### ISSUE THREAD

**Issue by cpwnd** [jlu-ilr-hydro/odmf#46]
The template file `odmf/webpage/template/wiki.html` has some missing resource files, this slows down the client rendering of the wiki website, since the files are tried to be fetched before browser rendering. Are the files still relevant? Files with similar names appear not to be in the repository @philippkraft 

https://github.com/jlu-ilr-hydro/odmf/blob/37a45edb372fef37976acdd07df3d667883ada48/odmf/webpage/templates/wiki.html#L8-L16

**Comment by philippkraft** [comment]
@bees4ever, you put in those links but never added the files to git - now they are lost :-(. I am going to remove this stuff, but can you add the alpha-video.js /.css files (if you still have them) to another branch? And perhaps describe here what purpose font-awesome served in the wiki page?

**Comment by philippkraft** [comment]
Issue solved.
By the way, I am doing a major refactoring of the whole package currently. I am closing this issue, but would still be interested in the files
