### ISSUE TITLE
Filter of dataset records does not work

### ISSUE THREAD

**Issue by thouska** [jlu-ilr-hydro/odmf#55]
A dataset has records. Usually thousands. Does can be filtered. However, setttings of the filter are not applied by the website.

**Comment by philippkraft** [comment]
Problem was a missing time date format and duplicate id in dataset-edit.html. Will be solved on next database update.

**Comment by thouska** [comment]
Was the already database updated? The problem is persisting so far...

**Comment by philippkraft** [comment]
Should be available on the server now. Please test.

**Comment by thouska** [comment]
Looks good to me, thx!
