### ISSUE TITLE
Changing Valuetype during calibration

### ISSUE THREAD

**Issue by thouska** [jlu-ilr-hydro/odmf#56]
Would be a helpful feature, as valuetype usually change during calibration of a dataset, e.g. water depth to stream depth

**Comment by philippkraft** [comment]
### How about this: 
After clicking on "calibrate", the valuetype of the target becomes the valuetype of the source and the "edit" tab of the dataset opens. So if you calibrate a "water depth" with a "stream depth" the  new value type becomes "stream depth". This can be changed in the "edit" tab, of course.

**Comment by thouska** [comment]
Thx, sounds very good!

**Comment by philippkraft** [comment]
Fixed in Chimaera: 37a45edb372fef37976acdd07df3d667883ada48
