### ISSUE TITLE
New Feature request: Plot data additional to statistics during import

### ISSUE THREAD

**Issue by thouska** [jlu-ilr-hydro/odmf#59]
Small plot for each item during import of files in download section, to visually check data befor starting import. 
Benefit: Would help to identify malfunctions in datasets, where the logger is saving values in a, statistically, realistic range, but still wrong data. Happens very often with Diver and EM50 loggers and is currently generating delays to detect and fix errors in the logger.

**Comment by philippkraft** [comment]
Fixed in cbec2c85f5b39bd0c66767eba6c21572b868cfef
