### ISSUE TITLE
Bug: Error when aggregating data on Plot Website

### ISSUE THREAD

**Issue by thouska** [jlu-ilr-hydro/odmf#67]
Happens after clicking on "csv" in the line-object, if a aggregation was set, e.g. daily.
The error is new and must be linked to recent changes:

500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/var/wsgi/odmf.schwingbach/venv/lib/python3.6/site-packages/pandas/core/generic.py", line 368, in _get_axis_number
    return cls._AXIS_TO_AXIS_NUMBER[axis]
KeyError: 'mean'

**Comment by thouska** [comment]
Any updates on this one? Current online version results in same error.

**Comment by philippkraft** [comment]
Sorry for leaving this simple task open for so long...
