### ISSUE TITLE
Adding of instrument at sites not possible

### ISSUE THREAD

**Issue by thouska** [jlu-ilr-hydro/odmf#69]
Menu has only the setting possibility for a date, but no insturment can be selected or added to a site.

Reminder for myself: #34 needs a Diver as a instrument, installed on 10.12.2020, data is already in the corresponding download section, but not imported yet.

**Comment by philippkraft** [comment]
Need to redesgin site.html l. 346-370, make as form that submits a complete installation. Get list of instruments with template.

**Comment by philippkraft** [comment]
After Add instrument the instument does not appear.

**Comment by philippkraft** [comment]
Works for me on server
