### ISSUE TITLE
Plotting a timeries with points instead of lines result in an error

### ISSUE THREAD

**Issue by thouska** [jlu-ilr-hydro/odmf#73]
Invalid value of type 'builtins.str' received for the 'symbol' property of scatter.marker
    Received value: 'o'

The 'symbol' property is an enumeration that may be specified as:
  - One of the following enumeration values:
        [0, '0', 'circle', 100, '100', 'circle-open', 200, '200',
        'circle-dot', 300, '

**Comment by philippkraft** [comment]
Ok, that was a zero, not an o.
