### ISSUE TITLE
Protect /datafiles from unauthorized users

### ISSUE THREAD

**Issue by philippkraft** [jlu-ilr-hydro/odmf#78]

**Comment by cpwnd** [comment]
Do you have already a solution layed out? If not, maybe this could be done as follows:

As I understand, the StaticServer serves the datafiles and media directories.
And the datafiles server should be non-public and media should be public.

https://github.com/jlu-ilr-hydro/odmf/blob/564c305a45c2048742819d932354ef03c6085ec2/odmf/webpage/static.py#L20-L24

For the constructor add a new role member or non_public flag. E.g. the role defaults to None or maybe group.guest? Or if a flag ist used, it defaults to true.

https://github.com/jlu-ilr-hydro/odmf/blob/564c305a45c2048742819d932354ef03c6085ec2/odmf/webpage/static.py#L79-L94

And either 
  1. include here `@expose_for(self.role)` 
  2. or call the `expose_for decorator` on return of the function `expose_for(self.role, filelist2html(p.iterdir())`
  3. or write your own decorator

Explained in this [example](1).

What do you think?

[1]: https://stackoverflow.com/a/10724898

**Comment by philippkraft** [comment]
On hold, solve together with #90.

**Comment by philippkraft** [comment]
Transferred to #90
