### ISSUE TITLE
Both plotting and showing records at site tab/level does not work

### ISSUE THREAD

**Issue by thouska** [jlu-ilr-hydro/odmf#80]
Now error is given, webpage remains empty

Can be tested anywhere, e.g. here:
https://fb09-pasig.umwelt.uni-giessen.de/schwingbach/dataset/68?site_id=1

**Comment by philippkraft** [comment]
First problem: typo (linestyle, not line)
Second problem: records are loaded with POST, not GET, fixed allowed method

**Comment by thouska** [comment]
Showing records works fine now, thx. Plotting still does not work, which is why I would like to reopen this issue.

**Comment by philippkraft** [comment]
Works for me, even with another username.

Please try to clear the cache of that site eg. for Firefox:
https://support.mozilla.org/en-US/kb/how-clear-firefox-cache

**Comment by thouska** [comment]
That helped :) works now. Thx!
Is it planed that the "Make interactive plot" switch has no functionality yet?

**Comment by philippkraft** [comment]
Going to close. Regarding Make interactive: the switch should disappear. However, if this:

https://plotly.com/python/pandas-backend/

works well, we can go for always interactive here as well as for the upload plot. Good place for contribution, PR welcome.

Relevant code:

## dataset.py

https://github.com/jlu-ilr-hydro/odmf/blob/f19796198360ea3857a2c4b67d14048dff9b9d89/odmf/webpage/db_editor/datasetpage.py#L414-L453

## dbimport.py

https://github.com/jlu-ilr-hydro/odmf/blob/f19796198360ea3857a2c4b67d14048dff9b9d89/odmf/webpage/filemanager/dbimport.py#L18-L32
