### ISSUE TITLE
Permissions of folders created by the web interface

### ISSUE THREAD

**Issue by DWindhorst** [jlu-ilr-hydro/odmf#88]
Folder created through the web interface of the database have the wrong read/write permissions.

**Comment by philippkraft** [comment]
This was a tough one: The issue happens only in the systemd service, not if the server is run from the normal user. Reason is [umask](https://en.wikipedia.org/wiki/Umask), which is different for a shell user than for a service user. Setting the UMask explicitly for the service solves the problem.
