### ISSUE TITLE
Lab upload with look up table

### ISSUE THREAD

**Issue by cpwnd** [jlu-ilr-hydro/odmf#9]
@thouska 
A configurable way (e.g. the .conf files) is requested, to map short tokens, which identify sample collection points, to site ids in the database. So records can be attached to the dataset they belong to.

Suggestion
```
; conf.file
...
sample_mapping={
    "F1": 79,
    "F2": 80,
    ...
}

**Comment by thouska** [comment]
I like your suggested way!

**Comment by philippkraft** [comment]
Replaced by #85
